#!/usr/bin/env node
import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { createBridge } from './bridge.js'
import { generateSecret, loadConfig } from './config.js'
import { BridgeClient } from './data-source.js'
import { createMcpServer } from './mcp.js'
import { Store } from './storage.js'

function usage(): never {
  process.stderr.write(`Usage:
  toss-place-mcp init             Create a safe local .env file
  toss-place-mcp bridge           Run the self-hosted bridge and remote MCP endpoint
  toss-place-mcp mcp              Run the local stdio MCP client (default)
  toss-place-mcp pairing-code     Create a one-time Toss POS pairing code
  toss-place-mcp doctor           Check bridge and Toss POS connection health
  toss-place-mcp print-config     Print Codex configuration guidance
`)
  process.exit(1)
}

async function init(): Promise<void> {
  const path = resolve('.env')
  if (existsSync(path)) throw new Error(`${path} already exists; it was not overwritten`)
  const token = generateSecret(36)
  const content = `# Generated by toss-place-mcp init. Never commit this file.\nTOSS_MCP_ACCESS_TOKEN=${token}\nTOSS_MCP_HOST=127.0.0.1\nTOSS_MCP_PORT=8787\nTOSS_MCP_PUBLIC_URL=http://127.0.0.1:8787\nTOSS_MCP_DATABASE_URL=sqlite:./data/toss-place.sqlite\nTOSS_MCP_BRIDGE_URL=http://127.0.0.1:8787\n`
  writeFileSync(path, content, { encoding: 'utf8', flag: 'wx', mode: 0o600 })
  process.stdout.write(`Created ${path} with mode 0600.\nNext: npm run bridge\n`)
}

async function bridge(): Promise<void> {
  const config = loadConfig()
  const store = await Store.open(config.databaseUrl)
  const app = await createBridge(config, store)
  const shutdown = async () => {
    await app.close()
    await store.close()
    process.exit(0)
  }
  process.once('SIGINT', () => void shutdown())
  process.once('SIGTERM', () => void shutdown())
  await app.listen({ host: config.host, port: config.port })
}

async function mcp(): Promise<void> {
  const config = loadConfig()
  const server = createMcpServer(new BridgeClient(config.bridgeUrl, config.accessToken))
  await server.connect(new StdioServerTransport())
}

async function bridgeRequest<T>(path: string, init?: RequestInit): Promise<T> {
  const config = loadConfig()
  const response = await fetch(new URL(path, config.bridgeUrl), {
    ...init,
    headers: {
      Authorization: `Bearer ${config.accessToken}`,
      'Content-Type': 'application/json',
      ...init?.headers,
    },
  })
  if (!response.ok) throw new Error(`Bridge returned ${response.status}: ${await response.text()}`)
  return (await response.json()) as T
}

async function createPairingCode(): Promise<void> {
  const pairing = await bridgeRequest<{ code: string; expiresAt: string; bridgeUrl: string }>(
    '/v1/admin/pairing-codes',
    { method: 'POST', body: JSON.stringify({ ttlMinutes: 15 }) },
  )
  process.stdout.write(
    `Bridge URL: ${pairing.bridgeUrl}\nPairing code: ${pairing.code}\nExpires: ${pairing.expiresAt}\n\nEnter the bridge URL and code in the Toss POS plugin settings.\n`,
  )
}

async function doctor(): Promise<void> {
  const config = loadConfig()
  const healthResponse = await fetch(new URL('/health', config.bridgeUrl))
  if (!healthResponse.ok) throw new Error(`Bridge health returned ${healthResponse.status}`)
  const connections = await bridgeRequest<
    Array<{
      merchantName: string
      merchantId: string
      lastSeenAt: string | null
      dataFreshnessSeconds: number | null
    }>
  >('/v1/data/connections')
  process.stdout.write(`Bridge: healthy (${config.bridgeUrl})\n`)
  if (!connections.length) {
    process.stdout.write('Toss POS: not paired\nNext: toss-place-mcp pairing-code\n')
    return
  }
  for (const connection of connections) {
    process.stdout.write(
      `Toss POS: ${connection.merchantName} (${connection.merchantId}), last seen ${connection.lastSeenAt ?? 'never'}, freshness ${connection.dataFreshnessSeconds ?? 'unknown'}s\n`,
    )
  }
}

function printConfig(): void {
  const config = loadConfig()
  process.stdout.write(`Local stdio (recommended):
  codex mcp add toss-place \\
    --env TOSS_MCP_BRIDGE_URL=${config.bridgeUrl} \\
    --env TOSS_MCP_ACCESS_TOKEN=<value-from-your-.env> \\
    -- npx -y toss-place-mcp mcp

Remote Streamable HTTP:
  Add URL ${new URL('/mcp', config.bridgeUrl)} and use TOSS_MCP_ACCESS_TOKEN as the bearer token.

Do not paste the real token into a repository or support request.
`)
}

async function main(): Promise<void> {
  const command = process.argv[2] ?? 'mcp'
  if (command === 'init') await init()
  else if (command === 'bridge') await bridge()
  else if (command === 'mcp') await mcp()
  else if (command === 'pairing-code') await createPairingCode()
  else if (command === 'doctor') await doctor()
  else if (command === 'print-config') printConfig()
  else usage()
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
  process.exit(1)
})
